### ISSUE TITLE
SMTP Emails no longer sending

### ISSUE THREAD

**Issue by CryoBuilt** [iot-dsa-v2/dslink-java-v2-mailer#17]
I have this running on over 50 units and I noticed that they are all started to fail within the last week. They fail with the status text: **Could not convert socket to TLS** 
I am using the smtp.office365.com host. 

Any ideas what is going on here?

**Comment by a-hansen** [comment]
Thanks CyroBuilt, ticket created internally, I'll keep you updated.

**Comment by a-hansen** [comment]
1.3.2 released, please confirm the fix.
